Move CSS to separate stylesheet
google/web-bsd-hunt pull request #13
Opened 2016-10-31 18:15 UTC by speakerbug

This moves the CSS to a separate stylesheet. It also updates the CSS for 'black' and 'red' to be their respective hex values.

2016-10-31 18:22 UTC, speakerbug commented
Sorry, there were a bunch of commits of me just trying to get my forked repo up to date with this branch's master. Feel free to just squash all of them.

2016-11-02 04:54 UTC, tadhunt requested changes
Please make the two minor changes commented in this review.  Additionally I'm about to send you a PR against this branch for the changes necessary for this change to work in App Engine.  (Need to teach App Engine where to find style.css)

2016-11-02 04:54 UTC, tadhunt commented on server-frontend/src/server-frontend/client/style.css
> +}
Please fix missing NL at EOF

2016-11-02 04:54 UTC, tadhunt commented on server-frontend/src/server-frontend/client/style.css
> +    background: #000;
Please s/#000/#000000/

2016-11-02 20:32 UTC, speakerbug commented on server-frontend/src/server-frontend/client/style.css
> +}
I always forget about the NL...

2016-11-02 20:37 UTC, speakerbug commented
Okay, those changes should be made now. I'm not exactly sure why the NL at EOF isn't showing up on the comment above since it should be in there now...let me know if you can't see it.

2016-11-05 23:07 UTC, tadhunt approved these changes
LGTM

2016-11-05 23:07 UTC, merged