CSS Updates
google/web-bsd-hunt pull request #3
Opened 2016-10-14 16:37 UTC by speakerbug

Updated CSS names to match typical naming conventions and put it in an
external style.css file.

2016-10-14 16:39 UTC, speakerbug commented
I signed it!

2016-10-27 03:27 UTC, tadhunt requested changes
I'm happy to accept the sets of changes from this PR, but please separate the syntax and semantics changes into two PRs. This PR currently does both syntax (moving the CSS into style.css) and semantic (renaming the CSS classes), which are logically separate.

2016-10-27 03:27 UTC, tadhunt commented on server-frontend/src/server-frontend/client/style.css
> +}
add missing newline

2016-10-27 19:17 UTC, speakerbug commented
I just created a new PR for the new naming conventions (#6) and once that's merged in I'll open a new PR to move it into an external stylesheet.

2016-10-27 19:17 UTC, closed without merging